# Configmap

kind:             ConfigMap
apiVersion:       v1
metadata:
  name:           wordpress-configmap
data:
  db-name:        wordpress
---
# Secret
kind:             Secret
apiVersion:       v1
metadata:
  name:           wordpress-secret
type:             Opaque
data:
  db-user:        dXNlcm5hbWU= # username
  db-password:    cGFzc3dvcmQ= # password
---
# PVC Wordpress

kind:             PersistentVolumeClaim
apiVersion:       v1
metadata:
  name:           wordpress-pvc
spec:
  accessModes:
                - ReadWriteOnce
  resources:
    requests:
      storage:    1Gi
  storageClassName: gp3-csi

---

# Service MariaDB
kind:               Service
apiVersion:         v1
metadata:
  name:             mariadb
spec:
  type:             ClusterIP
  ports:
  - port:           3306 # IP De balanceo
    targetPort:     3306 # Puerto del contenedor
  selector:
    app:            mariadb # *1

---
# Service Wordpress

kind:               Service
apiVersion:         v1
metadata:
  name:             wordpress
spec:
  type:             ClusterIP
  ports:
  - port:           8080
    targetPort:     8080
  selector:
    app:            wordpress

---
# Ingress
---

# Statefulset MariaDB

kind:                     StatefulSet
apiVersion:               apps/v1
metadata:
  name:                   mariadb
spec:
  serviceName:            mariadb # Entradas de DNS para cada replica INDEPENDIENTES
                                  # Al cargarlo, me da una entrada en dns llamada: mariadb-0.mariadb
                                  # Que me permite apuntar a la primera réplica.. En este caso, solo tengo 1...
                                  # Si tuviera varias, me daría también: mariadb-1.mariadb, mariadb-2.mariadb, etc.
  replicas:               1
  selector:
    matchLabels:
      app:                mariadb
  template:
    metadata:
      labels:
        app:              mariadb
    spec:
      containers:
      - name:               mariadb
        image:              mariadb:latest
        imagePullPolicy:    IfNotPresent
        ports:
        - containerPort:    3306
        env:
        - name:             MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name:         wordpress-secret
              key:          db-password
        - name:             MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name:         wordpress-configmap
              key:          db-name
        - name:             MYSQL_USER
          valueFrom:
            secretKeyRef:
              name:         wordpress-secret
              key:          db-user
        - name:             MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name:         wordpress-secret
              key:          db-password
        volumeMounts:
        - name:               mariadb-persistent-storage
          mountPath:          /var/lib/mysql
      #volumes:
      #- name:                 mariadb-persistent-storage
      #  persistentVolumeClaim:
      #    claimName:          mariadb-pvc
  volumeClaimTemplates:
  - metadata:
      name:                 mariadb-persistent-storage
    spec:
      accessModes:
                          - ReadWriteOnce
      resources:
        requests:
          storage:          1Gi
      storageClassName:     gp3-csi
---

# Deployment Wordpress + Apache

kind:               Deployment
apiVersion:         apps/v1
metadata:
  name:             wordpress
spec:
  replicas:         1
  selector:
    matchLabels:
      app:          wordpress
  template:
    metadata:
      labels:
        app:                  wordpress
    spec:
      containers:
      - name:                 wordpress
        image:                bitnami/wordpress:latest
        imagePullPolicy:      IfNotPresent
        ports:                # Documentación
        - containerPort:      8080
        env:
        - name:               WORDPRESS_DATABASE_HOST
          value:              mariadb
        - name:               ALLOW_EMPTY_PASSWORD
          value:              "yes"
        - name:               WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name:           wordpress-secret
              key:            db-user
        - name:               WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name:           wordpress-secret
              key:            db-password
        - name:               WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name:           wordpress-configmap
              key:            db-name
        volumeMounts:
        - name:               wordpress-persistent-storage
          mountPath:          /bitnami/wordpress
      volumes:
      - name:                 wordpress-persistent-storage
        persistentVolumeClaim:
          claimName:          wordpress-pvc


---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: wordpress
spec:
  to:
    kind: Service
    name: wordpress
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
